### ISSUE TITLE
Replit

### ISSUE THREAD

**Issue by Shkeffy** [caffeine-moe/CHAOS#1]
Hello, @caffeine01, @ling-nyc, and @sexnine, could one of you help me start this in Replit?

**Comment by sexnine** [comment]
Hey there @Shkeffy, I don't have too much experience with replit and have very little involvement with this project (which makes me unsure of why you decided to ask me lol) but it shouldn't be too hard :)

- Import the repo into replit
- Download the default config file from [here](https://caffeine.moe/CHAOS/config.json) and chuck it in the root of the project.
- Edit the config file as you wish
- Then you should be able to just run it (once again, little experience on replit so I don't know aha)

[This](https://docs.replit.com/tutorials/06-github-and-run-button) should help if you're having trouble with the first step.

If you have any other questions, I would highly suggest asking @caffeine01 :)

Good luck!

**Comment by Shkeffy** [comment]
> Hey there @Shkeffy, I don't have too much experience with replit and have very little involvement with this project (which makes me unsure of why you decided to ask me lol) but it shouldn't be too hard :)
> 
> * Import the repo into replit
> * Download the default config file from [here](https://caffeine.moe/CHAOS/config.json) and chuck it in the root of the project.
> * Edit the config file as you wish
> * Then you should be able to just run it (once again, little experience on replit so I don't know aha)
> 
> [This](https://docs.replit.com/tutorials/06-github-and-run-button) should help if you're having trouble with the first step.
> 
> If you have any other questions, I would highly suggest asking @caffeine01 :)
> 
> Good luck!

I just asked everyone pingable lol.

**Comment by Shkeffy** [comment]
I'll try all that out.

**Comment by caffeine01** [comment]
- Go to replit
- Click "Create" in the top left, a box should appear in the centre of the screen
- Click "Import from GitHub" in the top right of the box that appeared
- A different box should appear in place of the old one, inside of the text box named "GitHub URL" copy and paste this repo URL into said text box. (https://github.com/caffeine-moe/CHAOS/)
- After pasting the repo URL, click the big blue button at the bottom right of the box that says "Import from GitHub"
- Now you should be dropped in to the repl it repo it just created for you, at the right hand side of the page it should have a box with a small blue box saying ".replit" in the top right. In the bigger white box, click the drop down menu named "select language" that should contain "Bash" by default and then scroll and choose "Kotlin". In the same box there should be a text box named "configure the run button", in that paste "./gradlew ShadowJar" (without the quote marks). After that, click the "Done" button.
- The page will refresh and once it has finished loading click the big green button at the top of the page that says "Run"
### Compiling on replit will take a VERY long time (8 minutes LOL). Please don't complain as replits hardware is out of my control.
- After compiling, change the run variable thingy in the .replit file to "java -jar ~/{REPL NAME}/build/libs/CHAOS-all.jar" (repl name is usually CHAOS and obviously without curly brackets)
- Click Run again and this time it should launch the selfbot throwing an error that the config file was not found, it will automatically create a new one for you in the root of the project.
- Edit the config file as you wish
- Then you should be able to click Run again and now CHAOS is running on replit!

![image](https://user-images.githubusercontent.com/45857025/166167254-7ddff042-e354-4bfc-ad32-25128bb72f6d.png)

### RUNNING CHAOS ON REPLIT IS SIGNIFICANTLY SLOWER THAN RUNNING IT ON YOUR COMPUTER, AGAIN, PLEASE DO NOT COMPLAIN TO ME. THIS IS OUT OF MY CONTROL.


If you have any other questions relating to this, feel free to ask :)

**Comment by caffeine01** [comment]
closing as user hasn't replied for 2 days.

**Comment by Shkeffy** [comment]
Sorry for not replying, thank you!!!
