### ISSUE TITLE
Option to automatically pull token from Discord client

### ISSUE THREAD

**Issue by sexnine** [caffeine-moe/CHAOS#12]
If CHAOS recognizes an invalid format for a token or the client fails to login, ~offer to pull a token from the Discord client and try login again~.

**Edit**: that shit annoying so let's not do that.

**Comment by caffeine01** [comment]
i do need to handle login errors and token formatting. ill do that soon.

**Comment by sexnine** [comment]
I suggest that if CHAOS recognizes token hasn't been set or incorrect to tell the user more clearly instead of just not working.

Someone ran into this problem when they forgot to set a token and couldn't figure out why it didn't work as CHAOS wasn't producing any errors.

**Comment by caffeine01** [comment]
errors that the discord gateway sends SHOULD be handled properly but i can try and figure that out, will be added in v2.2.0

**Comment by caffeine01** [comment]
![image](https://user-images.githubusercontent.com/45857025/171844300-91697c7f-b27b-4eed-9731-926750b4048b.png)

**Comment by sexnine** [comment]
Sweet looks good 👌

Fixed in: 9a88c40da1681ceeb58e97a3ad18d40468848595
