### ISSUE TITLE
Make help page and command more helpful

### ISSUE THREAD

**Issue by sexnine** [caffeine-moe/CHAOS#13]
https://caffeine.moe/CHAOS/commands/

- [x] Add descriptions to commands on page
- [ ] Add descriptions to commands when running the command
- [x] Standardize correct usage messages (eg: [this](https://github.com/caffeine-moe/CHAOS/blob/main/src/main/kotlin/org/caffeine/chaos/commands/Spam.kt#L22) is not very clear, especially to someone who doesn't know what a string or int is)

**Comment by caffeine01** [comment]
yea no im not doing that thats pointless, i consider this done :).
