### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Shkeffy** [caffeine-moe/CHAOS#2]
Can I please have a list of all commands?

**Comment by caffeine01** [comment]
[commands](https://github.com/caffeine-moe/CHAOS/blob/main/src/main/kotlin/org/caffeine/chaos/commands/Commands.kt)

delete message delay is in config
![image](https://user-images.githubusercontent.com/45857025/167022462-7245eaf9-f949-41f0-987f-0eb6631c0a89.png)

**Comment by Shkeffy** [comment]
So you turn it off by changing 'enabled' to 'false'?

**Comment by Shkeffy** [comment]
Also, could I get a list of commands, ?cmds sends you to a page that does *not* have commands.

**Comment by Shkeffy** [comment]
Even when I have it at 'false', it still deletes it.

**Comment by Shkeffy** [comment]
I fixed the message deleting thing.

**Comment by Shkeffy** [comment]
@caffeine01 could I have a list of commands please?

**Comment by caffeine01** [comment]
It's in the link i sent above the image, but anyways.
val commandlist = arrayOf(
    "ping",
    "help",
    "cmds",
    "commands",
    "ip",
    "purge",
    "sclear",
    "spurge",
    "spam",
    "sspam",
    "backup",
    "avatar",
    "av",
    "exchange",
    "crypto",
    "coin",
    "clear",
    "token",
    "q",
    "quit",
    "selfdestruct",
    "lgdm",
    "leavegroups",
    "idle",
    "away",
    "dnd",
    "donotdisturb",
    "invisible",
    "offline",
    "online",
    "figlet",
    "upload"
)

**Comment by Shkeffy** [comment]
Oh thank you!
